### PR TITLE
Delete unvisible track

### PR DESCRIPTION
**Pull request by SangbumChoi**
there could be small error in QA but it works fine right now

### CODE REVIEW

**Comment by kdh0324** [comment]
There are some errors.
1. I can't effect animations more than two. (When I select the other effects, the new track is added in list and its name is right. But, there is before effect in video.)
2. I can't select range of track. (It is fixed in 1s.)

**Comment by SangbumChoi** [comment]
What does it mean about 'there is before effect in video' Does it means previous effects are colored on?
Specific description might be needed
2. Yes this one is now I have to work on it

**Comment by SangbumChoi** [comment]
@kdh0324 I reopened this pull reqeust and I think I solved all issues that you mentioned check and discuss freely
Additionally there was one more error that you didn't mentioned about I also fixed that error which was related with invisible track

**Comment by kdh0324** [comment]
@SangbumChoi 
There are still some errors.
1. I can't effect multiple errors in same duration.
2. I can't cancel effect by right clicking and select "Off Track"

**Pull request merged**
